// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaH-gQ8-4FT1l1upQpfXoHPTQHu6zkDsE',
    appId: '1:193816022772:web:5fcc81cfda229fee6158a1',
    messagingSenderId: '193816022772',
    projectId: 'fyp-gng-3d3cb',
    authDomain: 'fyp-gng-3d3cb.firebaseapp.com',
    storageBucket: 'fyp-gng-3d3cb.firebasestorage.app',
    measurementId: 'G-M73BRBKQL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6tlZ--gzfmEFkeGBL0teaOhS6gZts28',
    appId: '1:193816022772:android:569ef0b9b22cad9a6158a1',
    messagingSenderId: '193816022772',
    projectId: 'fyp-gng-3d3cb',
    storageBucket: 'fyp-gng-3d3cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpuHAeNZeZ3ELl_a5krh6xdzbuDfDVSac',
    appId: '1:193816022772:ios:996c85e5f1455e676158a1',
    messagingSenderId: '193816022772',
    projectId: 'fyp-gng-3d3cb',
    storageBucket: 'fyp-gng-3d3cb.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpuHAeNZeZ3ELl_a5krh6xdzbuDfDVSac',
    appId: '1:193816022772:ios:996c85e5f1455e676158a1',
    messagingSenderId: '193816022772',
    projectId: 'fyp-gng-3d3cb',
    storageBucket: 'fyp-gng-3d3cb.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaH-gQ8-4FT1l1upQpfXoHPTQHu6zkDsE',
    appId: '1:193816022772:web:da838400b471b2596158a1',
    messagingSenderId: '193816022772',
    projectId: 'fyp-gng-3d3cb',
    authDomain: 'fyp-gng-3d3cb.firebaseapp.com',
    storageBucket: 'fyp-gng-3d3cb.firebasestorage.app',
    measurementId: 'G-0KQV89RZXF',
  );
}
